package com.example.cora;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.telecom.ConnectionService;
import android.util.Log;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.OnFailureListener;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.FirebaseFirestore;

import org.w3c.dom.Text;

import java.util.HashMap;
import java.util.Map;

public class Register extends AppCompatActivity {

    //widget variables
    EditText firstNameEditText;
    EditText lastNameEditText;
    EditText emailEditText;
    EditText passwordEditText;
    Button registerBtn;
    Button loginBtn;

    //boolean used to check fields
    boolean valid = true;

    //for firebase authentication
    FirebaseAuth fAuth;

    //for firebase authentication database store
    FirebaseFirestore fStore;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_register);

        //
        fAuth = FirebaseAuth.getInstance();
        fStore = FirebaseFirestore.getInstance();

        firstNameEditText = findViewById(R.id.firstNameEditText);
        lastNameEditText = findViewById(R.id.lastNameEditText);
        emailEditText = findViewById(R.id.emailEditText);
        passwordEditText = findViewById(R.id.passwordEditText);
        registerBtn = findViewById(R.id.registerBtn);
        loginBtn = findViewById(R.id.loginBtn);

        //call checkField function for each widget
        checkField(firstNameEditText);
        checkField(lastNameEditText);
        checkField(emailEditText);
        checkField(passwordEditText);

        //if user input text is valid
        //start initialize user registration
        if(valid)
        {
            fAuth.createUserWithEmailAndPassword(emailEditText.getText().toString(), passwordEditText.getText().toString()).addOnCompleteListener(this, new OnCompleteListener<AuthResult>()
            {
                @Override
                public void onComplete(@NonNull Task<AuthResult> task)
                {
                    if (task.isSuccessful())
                    {
                        //designate current user
                        FirebaseUser user = fAuth.getCurrentUser();

                        //sign in success, update UI with the signed in user's info
                        Toast.makeText(Register.this, "Create Account Successful", Toast.LENGTH_SHORT).show();

                        //acquire current user id that was auto generated by firebase
                        DocumentReference df = fStore.collection("Users").document(user.getUid());

                        //create a map to get data from input and store into firebase
                        Map<String,Object> userInfo = new HashMap<>();
                        userInfo.put("FirstName",firstNameEditText.getText().toString());
                        userInfo.put("LastName",lastNameEditText.getText().toString());
                        userInfo.put("UserEmail",emailEditText.getText().toString());
                        userInfo.put("UserPassword",passwordEditText.getText().toString());

                        //specify if user is regular user or admin
                        userInfo.put("isUser", "1");

                        //import map to firebase
                        df.set(userInfo);

                        //once create account is successful, send user to main activity
                        startActivity(new Intent(getApplicationContext(),MainActivity.class));
                        //user can't go back to create account if they press back
                        finish();
                    }
                    else
                    {
                        Toast.makeText(Register.this, "Create Account Failed", Toast.LENGTH_SHORT).show();
                    }

                }
            })




        }
    }

    //function to check if text fields are empty
    public boolean checkField(EditText textField)
    {
        if(textField.getText().toString().isEmpty())
        {
            textField.setError("Error");
            valid = false;
        }
        else
        {
            valid = true;
        }

        return valid;
    }

}